version: '2'
services:
  inochihouse-app:
    image: inochihouse
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://inochihouse-postgresql:5432/inochihouse
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - SPRING_DATA_JEST_URI=http://inochihouse-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://inochihouse-elasticsearch:9200
    ports:
      - 8080:8080
  inochihouse-postgresql:
    extends:
      file: postgresql.yml
      service: inochihouse-postgresql
  inochihouse-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: inochihouse-elasticsearch
